shell_integration no-rc
font_size 12
hide_window_decorations yes
cursor_shape beam
confirm_os_window_close 0
enable_audio_bell no
tab_bar_style separator
tab_separator  |
input_delay 0
cursor_trail 1
cursor_trail_decay 0.07 0.15
sync_to_monitor no

include ./themes/noctalia.conf
