-- Colorscheme: doom-one, matching the system palette.
--
-- The rest of the desktop (kitty, btop, GTK, starship, Qt) is generated by
-- Noctalia from customPalettes.doomed in modules/features/noctalia.nix. Neovim
-- has no Noctalia template, so it gets the upstream doom-one plugin instead --
-- Noctalia's "Doomed" scheme is a port of the same doom-one palette, so the two
-- agree without hand-copying hex values here.
--
-- doom-one exposes its settings as globals rather than an opts table, so they
-- are set in init(), before the plugin loads. As with the previous theme,
-- letting the colorscheme clear every background (editor, dashboard, floats,
-- :terminal) avoids the black patches that chasing individual highlight groups
-- left behind, and lets the terminal's translucency show through Neovim.
-- To go opaque, set doom_one_transparent_background to false.
return {
  {
    "NTBBloodbath/doom-one.nvim",
    lazy = false,
    priority = 1000,
    init = function()
      vim.g.doom_one_transparent_background = true
      vim.g.doom_one_terminal_colors = true
      vim.g.doom_one_italic_comments = true
    end,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "doom-one",
    },
  },
}
